### ISSUE TITLE
Refactor funktioniert nicht (?)

### ISSUE THREAD

**Issue by mupek100** [ProPra16/programmierpraktikum-abschlussprojekt-halt-doch-einfach-mal-dein-maul#3]
Refactor will assertEquals nicht akzeptieren.
Könnte aber auch ein Fehler von mir sein.
Ein einfacher Test wie:

public void test(){
assertEquals(1,1);
}

sollte doch klappen oder nicht?

**Comment by asfer100** [comment]
Will man nach refactor, wird der Code bei Red und bei green kompiliert und danach die Tests ausgeführt. Also mit diesem Test kannst du garnicht bei green gewesen sein, da man nur zu green wechseln kann, wenn genau immer ein Test fehlschlägt.dieser Test ist aber immer wahr.

**Comment by mupek100** [comment]
Ich versuche mit dem Test oben von Green in Refactor zu kommen, aber Refactor will assertEquals nicht akzeptieren.
Also es kommt "cannot find symbol" als Fehler.
Probier mal aus, ob bei dir der gleiche Fehler kommt, eventuell liegt es nur an meinem PC.

**Comment by asfer100** [comment]
Ich versteh das nicht ganz. Hast du jetzt bei GREEN diesen Test geschrieben oder bei RED ?
Falls du bei RED diesen Test geschrieben hast, dann kannst du erst garnicht nach GREEN gekommen sein, weil dieser Test nicht fehlschlägt.
Falls du bei GREEN diesen Test geschrieben hast, sollte auch cannot find Symbol kommen, da bei GREEN Junit nicht importiert wird. Aber es ist ohnehin nicht vorgesehen in GREEN Tests zu schreiben.
In GREEN schreibt man Code, der den Test, den man in RED schreibt, besteht.

**Comment by mupek100** [comment]
Danke habs jetzt verstanden
