### ISSUE TITLE
TextArea nicht klickbar

### ISSUE THREAD

**Issue by mupek100** [ProPra16/programmierpraktikum-abschlussprojekt-halt-doch-einfach-mal-dein-maul#4]
Man kann keinen Text im TextArea in Red auswählen, aber schreiben.
Wenn man jedoch zu Green oder Refactor wechselt, kann man weder schreiben noch klicken.
Nur per Tab kann man zum Fenster navigieren und dann auch schreiben, klicken und Text auswählen.
Das komische ist: Nachdem mal einmal auf Tracking geht funktioniert alles normal.
Habt ihr das selbe Problem?

**Comment by asfer100** [comment]
Jep, selbe Problem auch bei mir.

**Comment by hblazer** [comment]
Bei mir auch
