### ISSUE TITLE
Besprechungstreffen eures Projekts

### ISSUE THREAD

**Issue by MrEbbinghaus** [ProPra16/programmierpraktikum-abschlussprojekt-halt-doch-einfach-mal-dein-maul#8]
Hallo,

Bitte sprecht mit mir einen Termin ab, wo ihr mir euer Projekt vorstellt, in eurem derzeitigen Zustand.
Von Problemen und Lösungen berichtet oder zu bestehenden Themen fragen stellt.

Der Termin sollte höchstens 30min lang sein. Es geht nur darum, zu sehen was ihr wie macht.

Gruß,

Björn

**Comment by mupek100** [comment]
Also wie wäre es mit Dienstag?

**Comment by MrEbbinghaus** [comment]
10:00?

**Comment by mupek100** [comment]
Hättest du eventuell gegen 12:30 Zeit?

**Comment by MrEbbinghaus** [comment]
Jap. Also steht das

**Comment by MrEbbinghaus** [comment]
Einen Ort werde ich euch morgen schicken

**Comment by mupek100** [comment]
Wir haben Raum 4 in der Nat.Bib gebucht, wenn es dir nichts ausmacht könnten wir ja das Treffen dort machen.
