### ISSUE TITLE
Wo sind die Protokolle?

### ISSUE THREAD

**Issue by bendisposto** [ProPra16/programmierpraktikum-abschlussprojekt-halt-doch-einfach-mal-dein-maul#9]

**Comment by lozac** [comment]
Im "gradle" branch sind 2 PDF-Dateien und eine .txt Datei, darin sind die Protokolle der vergangenen 3 Wochen enthalten.

**Comment by mupek100** [comment]
Hab ich jetzt auch in den master-Branch gepusht.
